# Generated by Django 4.2.5 on 2024-04-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_text_analiz', '0002_analiz_doks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analiz_doks',
            old_name='words',
            new_name='dic_words',
        ),
    ]
